### ISSUE TITLE
favicon 설정

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#23]
favicon 설정 부탁드립니다~

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/43e4e7ae-ff8d-456e-95b8-1624bbf1a1a7)

**Comment by Todari** [comment]
#29 
확인 해 주시고, close 해주세요~

**Comment by leegwichan** [comment]
확인했습니다! 고생하셨습니다!

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/0e258737-b2c6-4ebb-8455-6e5be01b4354)
