### ISSUE TITLE
프론트 '최근 편집'으로 조회 시, 정보 안바뀌는 문제

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#27]
'최근 편집'으로 조회 시, 해당 문서를 불러오지 않는 문제 발생

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/3f5b8296-8a15-4ccd-9029-494045d00b87)

**Comment by Todari** [comment]
@jinhokim98 에게 assignee 할당할게요~ 곧 해결될 문제로 알고 있어요

**Comment by Todari** [comment]
반영 완료 했습니다~
#25 
확인 후 close 해주세요~

**Comment by leegwichan** [comment]
넵 확인 했습니다! 고생하셨습니다!
