### ISSUE TITLE
모바일 화면에서 검색 창 불가

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#28]
해당 모바일 창 오른쪽 위 검색 버튼을 눌러도 아무 반응이 없습니다.
모바일 화면을 가로로 돌리면 검색 창이 나오는 것은 확인 헸습니다.

혹시 의도된 것인지 확인 부탁드립니다.

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/efe29c0f-0acb-4483-a394-258b0be9d8c7)

**Comment by leegwichan** [comment]
모바일 창에서 검색 가능한 것 확인했습니다!

추가적으로 언급하실 사항 없으시면 해당 Issue 닫아주세요!

@skiende74

**Comment by leegwichan** [comment]
@skiende74 관련 추가적인 이슈 있어 남깁니다.


### Now
'돋보기 마크'를 처음 클릭했을 경우에 검색창이 나타나는 것이 확인
이후에 클릭해도 아무런 반응이 없음 

### To - Be
이미 검색창이 활성화 된 경우, '돋보기 마크'를 클릭하면 검색창이 없던 이전 상태로 돌아갔으면 좋겠습니다.

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/b984ca2e-e0d3-4530-ad68-01940109c282)

**Comment by skiende74** [comment]
> @skiende74 관련 추가적인 이슈 있어 남깁니다.
> 
> ### Now
> '돋보기 마크'를 처음 클릭했을 경우에 검색창이 나타나는 것이 확인 이후에 클릭해도 아무런 반응이 없음
> 
> ### To - Be
> 이미 검색창이 활성화 된 경우, '돋보기 마크'를 클릭하면 검색창이 없던 이전 상태로 돌아갔으면 좋겠습니다.
> 
> ![Image](https://private-user-images.githubusercontent.com/44027393/319401504-b984ca2e-e0d3-4530-ad68-01940109c282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTMxMTMsIm5iZiI6MTcxMjE5MjgxMywicGF0aCI6Ii80NDAyNzM5My8zMTk0MDE1MDQtYjk4NGNhMmUtZTBkMy00NTMwLWFkNjgtMDE5NDAxMDljMjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAxMDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ODg0NDU0ODUzOGRmZjI4YzhlMjlmNjIzMWEzOWM2MTE1OTc0YzA4ZjQ1OTk1ZTI5NjBiZmFlNTA4OWY1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49M03-4LSf03_9dJop5S96UmB49KkCxWRUAu8UcgL2g)

토글방식으로 변경해보겠습니다.

**Comment by skiende74** [comment]
토글기능 반영하였습니다 :) 
close하겠습니다
