### ISSUE TITLE
문서 편집하기 시 전 편집자의 닉네임이 적혀있는 오류

### ISSUE THREAD

**Issue by Todari** [Crew-Wiki/frontend#34]
### as-is
기존의 문서 편집하기를 누른 경우 닉네임 입력 창에 마지막 편집자의 이름이 작성되어 있음.
![Image](https://github.com/Crew-Wiki/frontend/assets/85233397/875dace8-fd61-49e8-9c5f-2ebde0bca3cd)

### to-be
기존의 문서 편집하기를 누른 경우 편집자 입력 창이 비어져 있어야 함.

**Comment by masonkimseoul** [comment]
고생하셨습니다!

![Image](https://github.com/Crew-Wiki/frontend/assets/87306418/0b3cdf26-cf2a-47de-a157-b7881e37cde8)
