### ISSUE TITLE
[width값 < 768] 헤더 - 버튼 사이 갭 추가 요청

### ISSUE THREAD

**Issue by masonkimseoul** [Crew-Wiki/frontend#35]
![Image](https://github.com/Crew-Wiki/frontend/assets/87306418/a832035f-b481-4dfe-8143-55f263ef4e26)

![Image](https://github.com/Crew-Wiki/frontend/assets/87306418/851f97d0-44ab-4a86-814e-4ef1d07f193e)

페이지 컴포넌트와 헤더 사이의 center(?)에 버튼들이 위치하면 좀 더 좋을 것 같습니다!

**Comment by Todari** [comment]
#39 

확인하시고 close 해주세요~

**Comment by masonkimseoul** [comment]
![Image](https://github.com/Crew-Wiki/frontend/assets/87306418/071cc72f-ec37-476a-89ad-ac3fc5c36426)
