### ISSUE TITLE
"작성하기" 기능 중 제목이 중복되었을 경우

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#38]
### Now

중복된 제목이 있을 경우, UI로부터 아무런 에러 메시지를 받을 수 없음

### To - Be

문서에 중복된 제목이 있을 경우, 경고문을 띄워주었으면 좋겠다.

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/f7c7848c-e3a2-43b3-9778-42724f02f9a2)

**Comment by Todari** [comment]
FE 팀에서 인지하고 있던 사항이라 반영중에 있었습니다.
dev 브랜치 배포되면 노티드릴게요~

**Comment by jinhokim98** [comment]
이슈 해결했습니다. 확인 바랍니다!

**Comment by Todari** [comment]
#41

**Comment by leegwichan** [comment]
확인했습니다! 고생하셨습니다!

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/b47fcd4f-d206-491c-9a17-a1dfbd6f6fe5)
