### ISSUE TITLE
작성하기 및 편집하기 페이지에서 새로고침 시 문서 날아가는 문제

### ISSUE THREAD

**Issue by Todari** [Crew-Wiki/frontend#40]
### As-is
작성하기 및 편집하기 화면에서 새로고침을 하면 내용이 초기화됨

### To-be
변경한 문서가 저장되어야 함.

---
사용자 경험에서 매우 중요한 issue이지만,
릴리즈가 얼마 남지 않아서, 중요도를 낮추겠습니다.

**Comment by leegwichan** [comment]
글 작성하는 중에 새로고침이 되어도 해당 글이 유지되는 것 확인했습니다.

하지만 캐싱을 이용하셨다고 해서 여러 상황에서 테스트를 해보았습니다.
'취소하기' 버튼을 누른 이후에 다시 '편집하기' 버튼을 누르니 특정 조건이 갖추어졌을 때, 버그가 발생하네요.

## Now

특정 상황에서 '편집하기' 기능에서 취소 버튼을 누르고 다시 '편집하기' 버튼을 누른 경우, 빈 창이 띄워짐
(한번 수정한 이후에 취소 버튼을 누르고, 들어갔다 나왔다 다시 들어가면 빈 창이 띄워짐. 그리고 이 상태로 세션이 종료되지 않으면 해당 크루의 '편집하기'에 들어가면 계속 빈 창이 띄워짐)

## To - Be

'편집하기' 기능에서 취소 버튼을 누르고 다시 '편집하기' 버튼을 누른 경우, 현재 작성된 글이 불러와지도록 변경

## 현재 상황

해당 영상은 로컬 스토리지, 세션 스토리지, 쿠키를 전부 지운 후에 새로고침을 한번 하고 바로 찍은 영상입니다.

![update-cancel-error](https://github.com/Crew-Wiki/frontend/assets/44027393/7687012f-8c49-4005-b60d-01e514ec6b07)

세션 스토리지 상황

![image](https://github.com/Crew-Wiki/frontend/assets/44027393/6f21a4ec-c927-4fda-9c61-1d30d3f7a97a)

**Comment by Todari** [comment]
새로고침 정보 남아있는거 확인했습니다~!
그런데 지금 제가 재현해 보기로는, 편집을 완료해서 PUT 메소드를 요청 후에 지우거나 새로 편집된 친구를 불러와야 하는데,
이전에 저장해 놓은 로그를 불러오는 것 같습니다.

1. 문서 1.0 존재
2. 문서 1.0을 1.1로 편집 완료 후, 작성완료 버튼을 눌러 PUT
3. 그대로 문서 1.1의 편집하기 버튼을 누르면 문서 1.0 버전이 불러와짐.

제가 재현을 제대로 못 한 걸 수 있는데,
확인 해 주시면 감사하겠습니다~

**Comment by Todari** [comment]
위에 커찬이 작성한 것이랑 같이 확인해 주세요!

**Comment by skiende74** [comment]
PR 머지하였는데 확인부탁드립니다. :)

**Comment by leegwichan** [comment]
위에 두 가지 이슈 해결 확인 되었습니다!
하지만 뒤로가기를 할 때는 '편집하기'에서 수정했던 내용이 유지되지 않는 것을 확인했습니다.
인지해주시고 추후에 수정 부탁드리겠습니다!
MVP 공개가 얼마 남지 않아서 해당 이슈는 마무리하겠습니다.

**Comment by Todari** [comment]
번거로울 수 있겠지만, 추후 트랙킹 위해 이슈 하나 만들어 주세요!

**Comment by skiende74** [comment]
말해주신사안에 대해 추가PR 하였습니다. #73
