### ISSUE TITLE
유저가 글을 변경한 후에 "편집로그" 조회 시, 해당 유저의 "편집 로그"가 반영이 안됨

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#43]
### Now

내가 "편집하기"를 통해 편집한 후에 "편집로그"에 들어가면, 내가 편집한 로그가 들어있지 않음

### To-Be

내가 "편집하기"를 통해 편집한 후에 "편집로그"에 들어갔을 때, 내가 편집한 로그도 볼 수 있는 방법 필요.

1. (정확히 잘 모르지만) 캐싱 등을 사용하는 것으로 보이는데, 내가 편집하기를 한 순간, 해당 글 캐싱 풀기
2. 내역을 새로 불러올 수 있는 버튼(ex. 새로고침 버튼) 추가 

### 문제 상황
![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/0160fa74-6abf-40e0-b269-c18c05a1e22b)

### 현재 캐싱 상태
![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/f8f0a987-f8be-4910-80c7-2d5a97bc0ae9)

**Comment by masonkimseoul** [comment]
고생하셨습니다!

![Image](https://github.com/Crew-Wiki/frontend/assets/87306418/71bdcda7-4b70-407f-a688-135eb8c7c3ea)
