### ISSUE TITLE
다른 사진 올렸는데 동일한 사진이 등록되는 오류

### ISSUE THREAD

**Issue by jhon3242** [Crew-Wiki/frontend#45]
## as-is
<img width="965" alt="image" src="https://github.com/Crew-Wiki/frontend/assets/78288539/9ae3ade1-e840-457b-af64-81b021626244">
<img width="739" alt="image" src="https://github.com/Crew-Wiki/frontend/assets/78288539/317f0f06-fa34-46ef-a86c-0ebd48b064f5">
슬랙에서 이미지를 복사하여 붙여넣는 경우 서로 전혀 다른 이미지인데 등록하면 같은 이미지로 바뀌는 문제가 있습니다.

**Comment by Todari** [comment]
ఠࡇఠ 도저히 예상이 안가는데 확인해볼게요

**Comment by Todari** [comment]
라벨설정해주세요

**Comment by jhon3242** [comment]
> 라벨설정해주세요

제가 설정 권한이 없어서 그런지 라벨링 설정이 안돼요ㅠ

**Comment by masonkimseoul** [comment]
라벨 달아두었습니다!

**Comment by Todari** [comment]
혹시 재현 조건 자세히 적어주실 수 있나요?
어떤 경우에 이 문제가 생기는 건지 아직 파악하지 못했습니다

**Comment by jhon3242** [comment]
슬랙에 있는 이미지를 복붙했을 때 발생합니다!
서로 다른 두 이미지를 복붙했는데, 글 작성 버튼을 누르면 동일한 이미지가 올라가요!

**Comment by Todari** [comment]
로직 확인해 볼게용

**Comment by Todari** [comment]
혹시 지금도 재현 가능한거죠??? 할때마다 계속 문제 발생하는거죠?

**Comment by jhon3242** [comment]
제가 지금은 밖이라 한시간 정도 뒤에 확인해보겠습니다!

**Comment by Todari** [comment]
알게씀당~

**Comment by jhon3242** [comment]
동일하게 발생하네여
혹시 어떻게 재현하는지 이해하셨나요??

**Comment by Todari** [comment]
1. 슬랙에서 A 사진을 복사해서 붙여넣는다.
2. 슬랙에서 B 사진을 복사해서 붙여넣는다.
3. 등록 시 두 사진이 같은 사진이 된다.

재현해볼게용

**Comment by Todari** [comment]
재현 확인했어요 원인은 파일 이름이 같은걸로 올라가서 그렇습니다.
1. a라는 사진 복사 후 업로드
2. b라는 사진 복사 후 업로드
3. 이 경우 복사한 이미지는 file name이 없음
이 경우에 a, b 둘다 image.png 라는 이름으로 업로드 돼서 s3 bucket에 하나밖에 올라가지 않네요.
이미지 중복 처리해서 말씀드릴게요

**Comment by Todari** [comment]
작업 완료했고, merge 후 노티드릴게용

**Comment by Todari** [comment]
반영됐어용
