### ISSUE TITLE
문서 조회 시, 목차의 숫자를 클릭할 경우 해당하는 곳으로 이동 불가

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#47]
### Now

파란색으로 된 숫자(ex. 1, 2, 3, 3.1) 눌러도 아무 반응 없음

### To - Be

파란색으로 된 숫자(ex. 1, 2, 3, 3.1)를 누르면 해당 위치로 이동

### 기타 사항

- 해당 사항은 후순위 작업 대상입니다.
  - 아직까지는 문서양이 많은 사람이 거이 없어 중요도가 낮다고 판단됩니다.
  - 이번에 반영하기 힘드실 것 같다면, Issue 닫아주셔도 됩니다~

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/5e4c01cf-49ec-46cc-a496-d64d2e37285f)

**Comment by masonkimseoul** [comment]
고생하셨습니다!

<img width="192" alt="스크린샷 2024-04-04 13 43 51" src="https://github.com/Crew-Wiki/frontend/assets/87306418/575648f2-3575-460f-a49e-55105f733db4">
