### ISSUE TITLE
'편집하기' 화면에서 뒤로 간 후에 다시 '편집하기' 화면으로 들어왔을 경우, 수정했던 정보가 유지가 안됨

### ISSUE THREAD

**Issue by leegwichan** [Crew-Wiki/frontend#75]
### Now

'편집하기'를 수정한 이후에 뒤로가기를 한 후, 다시 버튼을 눌러 '편집하기'를 들어오면,
이전에 수정했던 내용이 반영되지 않음

### To - Be

뒤로가기를 하고 다시 들어와도 '편집하기'에서 수정한 사항을 그대로 유지

**Comment by skiende74** [comment]
제가 직접 해볼 때는 적용이 되는 거 같은데
제가 재연을 잘못한걸까요?
버그상황을 조금더자세히 보여주실수있을까요! 
(브라우저의 뒤로가기 했다가, 다시 편집하기 했을때)

캐싱기록이 글자입력후 (5초 뒤)라서 
글자입력후 5초 기다린 후 뒤로가기를 눌러주세요 !

**Comment by leegwichan** [comment]
제가 의도한대로는 안되는 것 같습니다.
혹시 추가 설명이 필요하시다면 DM 부탁드립니다.

![Image](https://github.com/Crew-Wiki/frontend/assets/44027393/518f2607-485a-4c54-ac85-3eab0d610d42)

**Comment by leegwichan** [comment]
5초를 유지할 경우, 되는 것 확인했습니다!
고생하셨습니다!
