### ISSUE TITLE
편집 및 작성 완료 후, 해당 문서의 작성 이력 남아있는 문제

### ISSUE THREAD

**Issue by Todari** [Crew-Wiki/frontend#81]
1. A 토다리 문서
2. A->B 토다리 문서 편집
3. 작성 완료 후 편집하기 클릭
4. A 문서의 정보가 보임

**Comment by jinhokim98** [comment]
이거 더 자세히 설명 가능할까요? 재연해보려고 하는데 어렵네용

**Comment by Todari** [comment]
음 이미지만 해당되는건가 제가 집에서 다시 테스트 해볼게요

**Comment by Todari** [comment]
제가 잘못테스트했나 재현이 불가능하네요 우선 close 하겠습니다
